# error_handling.py

import logging

def log_exception(logger, message):
    logger.exception(message)
